version: "2.2"
services:
  logstash:
    container_name: logstash
    network_mode: host
    user: 1000:1000
    image: docker.elastic.co/logstash/logstash:7.4.0
    volumes:
      - ./confs/insights_confs/:/usr/share/logstash/pipeline/
      - ./pipelines/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./lookups/:/usr/share/logstash/lookups/
      - ./mysql-connector-java-8.0.17.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.17.jar
      - ./mssql-jdbc-7.4.1.jre8.jar:/usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-7.4.1.jre8.jar
    environment:
      # LogStash container settings
      LS_JAVA_OPTS: "-Xmx4g -Xms4g"
      XPACK_MONITORING_ENABLED: "false"
      # Configuration files variables
      # Lookups
      CLIENTS_FILE: "/usr/share/logstash/lookups/clients.json"
      COUNTRIES_FILE: "/usr/share/logstash/lookups/countries.json"
      SERVICES_FILE: "/usr/share/logstash/lookups/services.json"
      CARRIERS_FILE: "/usr/share/logstash/lookups/carriers.json"
      STATUSES_FILE: "/usr/share/logstash/lookups/statuses.json"
      # DB connection settings
      JDBC_CONNECTION_URL: "jdbc:mysql://35.205.176.248:3306/returns?useCursorFetch=true"
      JDBC_CONNECTION_USER: "rebound_user"
      JDBC_CONNECTION_PASSWORD: "GJEMMzNkNG9m"
      # DB query variables
      DB_QUERY_SELECT_FROM_DATE: "20181101"
      DB_QUERY_SELECT_FROM_DATE_UNIX_TIMESTAMP: 1541030400
      # Cron job schedule
      CRON_SCHEDULE: "0 0 * * *"   # every day at UTC 00:00
      CRON_SCHEDULE_LOOKUPS: "0 23 * * *"  # every day at UTC 23:00
      # ES connection settings
      ES_HOST: "http://34.70.185.204:9200"
      ES_USER: "elastic"
      ES_PASSWORD: "82dgbsYKnBANA62f"