version: "2.2"
services:
  logstash:
    container_name: logstash
    network_mode: host
    user: 1000:1000
    image: docker.elastic.co/logstash/logstash:7.2.0
    volumes:
      # - ./confs/migration_item_base.returns.logstash.conf:/usr/share/logstash/pipeline/logstash_returns.conf
      # - ./confs/migration_item_base.orders.logstash.conf:/usr/share/logstash/pipeline/logstash_orders.conf
      - ./confs/migration_order_base.returns.logstash.conf:/usr/share/logstash/pipeline/logstash_returns.conf
      - ./confs/migration_order_base.orders.logstash.conf:/usr/share/logstash/pipeline/logstash_orders.conf
      - ./pipelines/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./mysql-connector-java-8.0.17.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.17.jar
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
      XPACK_MONITORING_ENABLED: "false"
    
  es:
    container_name: es
    network_mode: host
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      discovery.type: single-node
      cluster.name: "docker-cluster"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./esdata:/usr/share/elasticsearch/data