version: "2.2"
services:
  logstash:
    container_name: logstash
    network_mode: host
    user: 1000:1000
    image: docker.elastic.co/logstash/logstash:7.2.0
    volumes:
      - ./confs/replica_db.logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./mysql-connector-java-8.0.17.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.17.jar
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
      XPACK_MONITORING_ENABLED: "false"